name: 'Test Report'

on:
  workflow_run:
    workflows: [ CI ]                     
    types: [ completed ]

jobs:
  report: 
    runs-on: ubuntu-latest  
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: junit test report
          path: rest-adapter/target/surefire-reports/*.xml,core/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
